```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, cache=TRUE)
```

```{r Packages, include=FALSE}
require(ggplot2)
require(tidyr)
require(dplyr)
require(grid)
require(gridExtra)
require(lubridate)
```

```{r Load csv}
dante <- read.csv("dante_logbook-sheet1.csv")
```

```{r Manipiulation}
dante$date1 <- parse_date_time(paste(dante$date, " ", dante$time), "dmy hms")
levels(dante$boob) <- c("bottle", "both", "cluster", "right", "left")
dante$calmosyl <- as.logical(dante$calmosyl)

dante$date2 <- dante$date1
for(i in 1:length(dante$date1)){
    minute(dante$date2[i]) <- round(minute(dante$date2[i])/10, 0)*10
} ## Round time to 10 inutes steps
dante$interval[1]<-0; for(i in 2:length(dante$date2)){dante$interval[i] <- round(dante$date2[i]-dante$date2[i-1], 2)}## Interval
dante$interval[dante$interval > 12] <- dante$interval[dante$interval > 12]/60 ##Adjust minutes to fraction of an hour
week_tag <- function() {
    origin <- as.POSIXct(strptime("2015-08-03 00:00:00", "%Y-%m-%d %H:%M:%S"))
    
}
```


```{r First look}
##Longer interval
print(paste("Max interval:", max(dante$interval[dante$interval < 10]), "in date", dante$date1[which.max(dante$interval[dante$interval < 10])-1])) 
##Interval length distribution
ggplot(dante, aes(x = interval)) + geom_histogram(binwidth = .5, colour = "black", fill = "cadetblue3")
summary(dante$interval)
```